language: python
matrix:
  include:
    - os: linux
      python: 3.5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      env:
        - PROTOBUF_VERSION=3.4.0
    - os: osx
      python: 3.6
      env:
        - PROTOBUF_VERSION=3.6.1
install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
    export PATH="$PATH:$HOME/bin" ;
    echo "PATH=$PATH";
    fi
  # Install OS-specific dependencies
  - sh "./ci-scripts/install-${TRAVIS_OS_NAME}.sh"
  # Upgrade protobuf python
  - pip3 install --upgrade protobuf
  - pip3 install "protobuf==${PROTOBUF_VERSION}" ecdsa
  - pip install --upgrade protobuf
  # Install go
  - eval "$(gimme 1.10)"
script:
  - make all
notifications:
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

